### ISSUE TITLE
[Bug] `invoice_id` is not unique

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_zuora#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Reference:
https://github.com/fivetran/dbt_zuora/blob/c72916265d078dd706fac3b543a13c0027b69a31/models/zuora.yml#L179C17-L179C17

`invoice id` is not unique in this table since there is a one to many relationship between invoices and payments, as well as between invoices and credit balance adjustments.

### Relevant error log or model output

```shell
unique test returns an error.
```

### Expected behavior

The way the logic is currently defined, this test probably shouldn't be there.

### dbt Project configurations

N/A

### Package versions

  - package: fivetran/zuora
    version: 0.1.0

### What database are you using dbt with?

snowflake

### dbt Version

1.5

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @raphaelvarieras thanks for opening this issue and sharing the test failure you are experiencing. You mentioned that this test shouldn't be there at all. My understanding is that based on the transformation logic, the output of this model should in fact result in unique invoice_id records. 

Would you be able to share the duplicates you are seeing. This will allow me to better understand the grain and if we need to update the transformation logic, or as you mentioned remove the test.

**Comment by raphaelvarieras** [comment]
Sure, I've got tons of duplicates!

See below the result of the following query:
```
SELECT i.invoice_id, ip.invoice_payment_id, p.payment_id, cba.credit_balance_adjustment_id
FROM zello_db.stg_zuora.stg_zuora__invoice i
LEFT JOIN zello_db.stg_zuora.stg_zuora__invoice_payment ip on ip.invoice_id = i.invoice_id
LEFT JOIN zello_db.stg_zuora.stg_zuora__payment p on p.payment_id = ip.payment_id
LEFT JOIN zello_db.stg_zuora.stg_zuora__credit_balance_adjustment cba on cba.invoice_id = i.invoice_id
QUALIFY count(*) over (partition by i.invoice_id) > 1;
```

32k rows:
<img width="2302" alt="image" src="https://github.com/fivetran/dbt_zuora/assets/6558178/ef5e30c3-3e8c-4a0f-bbcb-fffca4730988">

I believe the issue lies in this joining logic [here](https://github.com/fivetran/dbt_zuora/blob/c72916265d078dd706fac3b543a13c0027b69a31/models/intermediate/int_zuora__billing_enriched.sql#L119): the cardinality of the results is the product of the number of invoices by the number of payments by the number of credit balance adjustments. And I certainly have a number of invoices for which we collected multiple independent payments, or had to process multiple credit balance adjustments.

**Comment by fivetran-avinash** [comment]
Hi @[raphaelvarieras](https://github.com/raphaelvarieras), thanks for investigating this further! We will be picking up development on this project in our current sprint, starting tomorrow!

It looks as if in our developmental data we did not have invoices with multiple payments, invoice payments or credit balance adjustments. There should definitely be a uniqueness test on this model though. Before progressing further I was hoping to get your thoughts on the following. Which solution do you believe would be preferred in your case so we may have a better understanding of the ideal model to use in your analysis:

- We maintain the same grain you currently see, but simply modify the definition of the table to reflect the actual grain you are seeing and adjust the test as well (unique invoice, payment, credit balance adjustment).
- We modify the model entirely to reflect the initial grain we intended to recreate (unique invoices).

[Could you schedule some time to chat with us during our office hours, ](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2023-08)preferably next week? This could help accelerate our work in fixing this. If none of those times work out please reply back and we can find a time that works for both of us.

Cheers!

**Comment by raphaelvarieras** [comment]
> [Could you schedule some time to chat with us during our office hours, ](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2023-08)preferably next week?

I'm unfortunately on PTO so won't be able to schedule anything this week. That said, I am not entirely sure what the best solution might be since I was never able to review the analyses from the package. If you want to leverage invoice amounts then you'll need to normalize the models. If on the other hand you want to sum payment amounts, you might be fine testing unicity on a combination of columns with invoice ID and payment ID. Same goes for credit balance adjustments.

**Comment by fivetran-avinash** [comment]
Hi @raphaelvarieras, hope you had a good PTO!

We have significantly revamped `zuora__biling_history` to make `invoice_id` the grain. You can see a list of changes here: https://github.com/fivetran/dbt_zuora/releases/tag/v0.2.0

We recommend you update to the latest version of the package and test it out and let us know your feedback. Thanks again for being a great thought partner!
